'use strict';
/* Regenerates src/lib/sample-document.js from the real document template, so
   the browser demo shows a genuine render rather than a hand-written mock.
   Run with: npm run build:sample */
const fs = require('fs');
const path = require('path');
const { renderDocument } = require('../electron/lib/document-template.js');
const { DEMO_DRAFT, DEMO_BRAND, DEMO_ITEMS } = require('./sample-data.js');

const html = renderDocument(DEMO_DRAFT, DEMO_BRAND, DEMO_ITEMS, {});
const out = path.join(__dirname, '..', 'src', 'lib', 'sample-document.js');
fs.writeFileSync(out, [
  '/* Generated by scripts/build-sample.js from the real document template.',
  '   Used only by the browser demo, where the main process is unavailable. */',
  `export const SAMPLE_DOCUMENT_HTML = ${JSON.stringify(html)};`,
  '',
].join('\n'));
console.log(`Wrote ${out} (${html.length} chars)`);
